### ISSUE TITLE
A specified parameter was not correct / spec.location.pool

### ISSUE THREAD

**Issue by tischenko** [JetBrains/teamcity-vmware-plugin#11]
Hi,

I try to use this plugin to manage VMs in vSphere. Plugin version: 0.5.158. 

![screen shot 2016-05-05 at 09 55 02](https://cloud.githubusercontent.com/assets/1525190/15038830/a75f57e6-12a7-11e6-9e25-58a8416e4a60.png)
![screen shot 2016-05-05 at 09 51 28](https://cloud.githubusercontent.com/assets/1525190/15039037/8794090a-12a9-11e6-965f-48e62b002e69.png)

Trace looks like this:

```
[2016-05-04 09:32:00,335]   INFO [le'{id=vmw-1} 1] - clouds.vmware.VmwareCloudImage - Image teamcity-ansible-buildagent, remove instance teamcity-ansible-buildagent-27704 
[2016-05-04 09:32:02,001]   INFO [uled executor 4] - .server.impl.CloudEventsLogger - Cloud instance has gone (is not reported by cloud profile): profileId=vmw-1, imageId=teamcity-ansible-buildagent, instanceId=teamcity-ansible-buildagent-27704 
[2016-05-04 09:32:04,061]  DEBUG [4 Flush Queue 1] - clouds.vmware.VmwareCloudImage - Instances count: 0 [], can start more: true 
[2016-05-04 09:32:04,061]  DEBUG [4 Flush Queue 1] - clouds.vmware.VmwareCloudImage - Instances count: 0 [], can start more: true 
[2016-05-04 09:32:04,061]  DEBUG [4 Flush Queue 1] - clouds.vmware.VmwareCloudImage - Instances count: 0 [], can start more: true 
[2016-05-04 09:32:04,061]  DEBUG [4 Flush Queue 1] - .server.impl.CloudEventsLogger - BeforeStart instance: profile 'vSphere'{id=vmw-1}, VmwareCloudImage{myName='teamcity-ansible-buildagent'} 
[2016-05-04 09:32:04,061]   INFO [4 Flush Queue 1] - .instances.StartInstanceAction - Starting cloud instance: profile 'vSphere'{id=vmw-1}, VmwareCloudImage{myName='teamcity-ansible-buildagent'}, hash=4IgxAisz8Bh4pLeCWXZMrzYXBT1O2mOW, reason=Automatic start: Start instance to get instance agent details, CloudInstanceUserData{myAgentName=<none>, myAuthToken='', myServerAddress='http://x.x.x.x', myProfileDescription='profile 'vSphere'{id=vmw-1}', myIdleTimeout=40 min, myCustomAgentConfigurationParameters={system.cloud.profile_id=vmw-1, teamcity.cloud.agent.terminate.after.build=true, teamcity.cloud.instance.hash=4IgxAisz8Bh4pLeCWXZMrzYXBT1O2mOW}} 
[2016-05-04 09:32:04,061]  DEBUG [4 Flush Queue 1] - clouds.vmware.VmwareCloudImage - Instances count: 0 [], can start more: true 
[2016-05-04 09:32:04,061]   INFO [4 Flush Queue 1] - clouds.vmware.VmwareCloudImage - Will create a new VM with name teamcity-ansible-buildagent-27705 
[2016-05-04 09:32:04,077]   INFO [4 Flush Queue 1] - clouds.vmware.VmwareCloudImage - Will clone for teamcity-ansible-buildagent-27705: true 
[2016-05-04 09:32:04,077]   INFO [4 Flush Queue 1] - uds.base.AbstractCloudInstance - Changing teamcity-ansible-buildagent-27705(11053141) status from Unknown to Scheduled to start  
[2016-05-04 09:32:04,077]   INFO [4 Flush Queue 1] - clouds.vmware.VmwareCloudImage - Image teamcity-ansible-buildagent, put instance teamcity-ansible-buildagent-27705 
[2016-05-04 09:32:04,077]   INFO [4 Flush Queue 1] - nnector.VMWareApiConnectorImpl - Attempting to clone VM teamcity-ansible-buildagent into teamcity-ansible-buildagent-27705 
[2016-05-04 09:32:04,104]   INFO [4 Flush Queue 1] - nnector.VMWareApiConnectorImpl - Snapshot name is not specified. Will clone latest VM state 
[2016-05-04 09:32:04,117]   INFO [4 Flush Queue 1] - .server.impl.CloudEventsLogger - Cloud instance entered 'scheduled to start' state, profile 'vSphere'{id=vmw-1}, VmwareCloudInstance{myInstanceName='teamcity-ansible-buildagent-27705'myState='SCHEDULED_TO_START'myStatusUpdateTime='Wed May 04 09:32:04 GMT 2016'}

[2016-05-04 09:32:04,117]   INFO [4 Flush Queue 1] - .server.impl.CloudEventsLogger - Cloud instance start succeeded: profile 'vSphere'{id=vmw-1}, VmwareCloudInstance{myInstanceName='teamcity-ansible-buildagent-27705'myState='SCHEDULED_TO_START'myStatusUpdateTime='Wed May 04 09:32:04 GMT 2016'}

[2016-05-04 09:32:05,246]   INFO [le'{id=vmw-1} 1] - uds.base.AbstractCloudInstance - Changing teamcity-ansible-buildagent-27705(11053141) status from Scheduled to start to Error  
[2016-05-04 09:32:05,247]   WARN [le'{id=vmw-1} 1] - clouds.vmware.VmwareCloudImage - An error occurred: A specified parameter was not correct. 
spec.location.pool during processing teamcity-ansible-buildagent-27705: java.lang.Exception: A specified parameter was not correct. 
spec.location.pool 
[2016-05-04 09:32:05,247]  DEBUG [le'{id=vmw-1} 1] - clouds.vmware.VmwareCloudImage - An error occurred: A specified parameter was not correct. 
spec.location.pool during processing teamcity-ansible-buildagent-27705 
java.lang.Exception: A specified parameter was not correct. 
spec.location.pool
    at jetbrains.buildServer.clouds.vmware.connector.VmwareTaskWrapper$2.get(VmwareTaskWrapper.java:130)
    at jetbrains.buildServer.clouds.vmware.connector.VmwareTaskWrapper$2.get(VmwareTaskWrapper.java:86)
    at jetbrains.buildServer.clouds.base.connector.CloudAsyncTaskExecutor.processSingleTask(CloudAsyncTaskExecutor.java:98)
    at jetbrains.buildServer.clouds.base.connector.CloudAsyncTaskExecutor.checkTasks(CloudAsyncTaskExecutor.java:86)
    at jetbrains.buildServer.clouds.base.connector.CloudAsyncTaskExecutor.access$000(CloudAsyncTaskExecutor.java:34)
    at jetbrains.buildServer.clouds.base.connector.CloudAsyncTaskExecutor$1.run(CloudAsyncTaskExecutor.java:48)
    at jetbrains.buildServer.util.NamedThreadFactory.executeWithNewThreadName(NamedThreadFactory.java:89)
    at jetbrains.buildServer.clouds.base.connector.CloudAsyncTaskExecutor$2.run(CloudAsyncTaskExecutor.java:65)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
```

It seems that the problem relates to 'Resource pool' option in plugin settings. But I don't have any available pools in drop-down menu. Whether is this setting mandatory?

Also I can't see snapshots available for several VMs in plugin settings, but I can see these snapshots in vSphere web client. Meanwhile our IT department assures that permissions were set totally correctly in vSphere. Is there any documentation about how to manage vSphere permissions to use all features of this plugin with Teamcity?

**Comment by paksv** [comment]
1) It should always be a "<default>" option. Please use it.
2) About not seeing all snapshots please attach teamcity-clouds.log as well as information about your vSphere/vCenter (type, version)

Also, please note that if you are using a free version of vSphere, the plugin won't work, because API calls that changes VM state are only available in paid versions.

**Comment by tischenko** [comment]
Hi, sorry for late reply. But we still have stuck with vSphere integration.

I had to downgrade the plugin to 0.5.89 to solve the problem with _spec.location.pool_. I tried using different settings in the latest plugin, but always got the same error about _spec.location.pool_. Now it works, but I get another error :)
Problem with seeing all snapshots probably related to vSphere permissions. Currently it works OK as well.

We use vSphere 5.5.0 (build 2183111), licensed as "Standard". Currently we have several clusters and datastores in use if this matters.

Our teamcity-clouds.log looks like this:
```
[2016-05-20 01:42:31,654]  DEBUG [1 Flush Queue 1] - clouds.vmware.VmwareCloudImage - Running count: 0 [], can start more: true 
[2016-05-20 01:42:31,654]   INFO [1 Flush Queue 1] - clouds.vmware.VmwareCloudImage - Will create a new VM with name teamcity-centos67-1-clone-0520-014231bb 
[2016-05-20 01:42:31,682]   INFO [1 Flush Queue 1] - clouds.vmware.VmwareCloudImage - Will clone for teamcity-centos67-1-clone-0520-014231bb: true 
[2016-05-20 01:42:31,682]   INFO [1 Flush Queue 1] - uds.vmware.VmwareCloudInstance - Changing teamcity-centos67-1-clone-0520-014231bb(3335e3ff) status from Unknown to Scheduled to start  
[2016-05-20 01:42:31,682]   INFO [1 Flush Queue 1] - clouds.vmware.VmwareCloudImage - Image teamcity-centos67-1, put instance teamcity-centos67-1-clone-0520-014231bb 
[2016-05-20 01:42:31,682]   INFO [1 Flush Queue 1] - nnector.VMWareApiConnectorImpl - Attempting to clone VM teamcity-centos67-1 into teamcity-centos67-1-clone-0520-014231bb 
[2016-05-20 01:42:31,749]   INFO [1 Flush Queue 1] - nnector.VMWareApiConnectorImpl - Snapshot name is not specified. Will clone latest VM state 
[2016-05-20 01:42:31,771]   INFO [1 Flush Queue 1] - .server.impl.CloudEventsLogger - Cloud instance entered 'scheduled to start' state, profile 'vSphere RV'{id=vmw-1}, VmwareCloudInstance{myName='teamcity-centos67-1-clone-0520-014231bb'} 
[2016-05-20 01:42:31,771]   INFO [1 Flush Queue 1] - .server.impl.CloudEventsLogger - Cloud instance start succeeded: profile 'vSphere RV'{id=vmw-1}, VmwareCloudInstance{myName='teamcity-centos67-1-clone-0520-014231bb'} 
[2016-05-20 01:42:37,707]  DEBUG [nio-8111-exec-2] - clouds.vmware.VmwareCloudImage - Running count: 1 [teamcity-centos67-1-clone-0520-014231bb], can start more: false 
[2016-05-20 01:42:39,367]   WARN [le'{id=vmw-1} 1] - clouds.vmware.VmwareCloudImage - An error occured: A component of the virtual machine is not accessible on the host. during processing teamcity-centos67-1-clone-0520-014231bb 
[2016-05-20 01:42:39,367]   INFO [le'{id=vmw-1} 1] - clouds.vmware.VmwareCloudImage - Image teamcity-centos67-1, remove instance teamcity-centos67-1-clone-0520-014231bb 
```

So the error message is:
```
[2016-05-20 01:42:39,367]   WARN [le'{id=vmw-1} 1] - clouds.vmware.VmwareCloudImage - An error occured: A component of the virtual machine is not accessible on the host. during processing teamcity-centos67-1-clone-0520-014231bb 
```

This error is the same for VMs and templates. I've tried both ways. Using vSphere Web Client the same operation works without any issues.

**Comment by paksv** [comment]
@tischenko looks like https://kb.vmware.com/kb/1021563

**Comment by paksv** [comment]
Corresponding issue in TC tracker: https://youtrack.jetbrains.com/issue/TW-49004
