### ISSUE TITLE
ManagedObjectNotFound

### ISSUE THREAD

**Issue by nap** [JetBrains/teamcity-vmware-plugin#13]
Hi, I'm using `0.5.125` on a `teamcity-9.1.7` and I see a lot of the following error.
This also cause the plugin to stop managing object that it create inside vSphere effectively leaving a bunch of stopped VM and eventually overflowing the cluster's storage capacity.

```
[2017-02-07 12:46:33,609]   WARN [re'{id=vmw-1} 2] - base.tasks.UpdateInstancesTask - java.lang.RuntimeException: java.rmi.RemoteException: VI SDK invoke exception:com.vmware.vim25.ManagedObjectNotFound 
java.lang.RuntimeException: java.rmi.RemoteException: VI SDK invoke exception:com.vmware.vim25.ManagedObjectNotFound
	at com.vmware.vim25.mo.ManagedObject.retrieveObjectProperties(ManagedObject.java:158)
	at com.vmware.vim25.mo.ManagedObject.getCurrentProperty(ManagedObject.java:179)
	at com.vmware.vim25.mo.ManagedEntity.getName(ManagedEntity.java:99)
	at jetbrains.buildServer.clouds.vmware.connector.VMWareApiConnectorImpl.findAllEntitiesAsMap(VMWareApiConnectorImpl.java:178)
	at jetbrains.buildServer.clouds.vmware.connector.VMWareApiConnectorImpl.listImageInstances(VMWareApiConnectorImpl.java:213)
	at jetbrains.buildServer.clouds.vmware.connector.VMWareApiConnectorImpl.listImageInstances(VMWareApiConnectorImpl.java:53)
	at jetbrains.buildServer.clouds.base.tasks.UpdateInstancesTask.run(UpdateInstancesTask.java:59)
	at jetbrains.buildServer.util.NamedThreadFactory.executeWithNewThreadName(NamedThreadFactory.java:89)
	at jetbrains.buildServer.clouds.base.connector.CloudAsyncTaskExecutor$2.run(CloudAsyncTaskExecutor.java:62)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.rmi.RemoteException: VI SDK invoke exception:com.vmware.vim25.ManagedObjectNotFound
	at com.vmware.vim25.ws.WSClient.invoke(WSClient.java:122)
	at com.vmware.vim25.ws.VimStub.retrieveProperties(VimStub.java:72)
	at com.vmware.vim25.mo.PropertyCollector.retrieveProperties(PropertyCollector.java:107)
	at com.vmware.vim25.mo.ManagedObject.retrieveObjectProperties(ManagedObject.java:155)
	... 15 more
```

I can see the following inside teamcity with the same error message.
![screen shot 2017-02-07 at 12 52 15 pm](https://cloud.githubusercontent.com/assets/2131451/22704175/c17a8480-ed34-11e6-830b-45d178f387de.png)

it also happen often:
```
$ sed -e 1b -e '$!d' teamcity-clouds.log
[2017-02-06 16:21:16,286]   INFO [5 Flush Queue 1] - clouds.vmware.VmwareCloudImage - Will create a new VM with name TW-test-34063 
[2017-02-07 14:16:59,531]   INFO [14:14:58 Ping 1] - ver.instances.AgentRemoverImpl - Removing cloud agent "PTS-CD" {id=90105} because: Cloud instance (id=PTS-CD, imageId=PTS-CD, profileId=vmw-1) has gone (is not reported by cloud profile) 
$ grep -E "^java.lang.*ManagedObjectNotFound" teamcity-clouds.log  | wc -l
175
```

`175` occurrence between `2017-02-06 16:21:16` and `2017-02-07 14:16:59`

I use vSphere 5.5
Thanks.

**Comment by nap** [comment]
@paksv let me know if I can do anything to help figure this out. I'd be happy to help.
Thanks.

**Comment by paksv** [comment]
This usually happens, when one of the images you configured in the profile doesn't exist/available anymore. Please check this first

**Comment by nap** [comment]
I can confirm that the image is still there.

**Comment by paksv** [comment]
Please post here the profile error details

**Comment by nap** [comment]
```
java.rmi.RemoteException: VI SDK invoke exception:com.vmware.vim25.ManagedObjectNotFound 
Hide stacktrace
java.lang.RuntimeException: java.rmi.RemoteException: VI SDK invoke exception:com.vmware.vim25.ManagedObjectNotFoundjava.lang.RuntimeException: java.rmi.RemoteException: VI SDK invoke exception:com.vmware.vim25.ManagedObjectNotFound
at com.vmware.vim25.mo.ManagedObject.retrieveObjectProperties(ManagedObject.java:158)
at com.vmware.vim25.mo.ManagedObject.getCurrentProperty(ManagedObject.java:179)
at com.vmware.vim25.mo.ManagedObject.getManagedObject(ManagedObject.java:369)
at com.vmware.vim25.mo.ManagedEntity.getParent(ManagedEntity.java:109)
at jetbrains.buildServer.clouds.vmware.connector.VmwareUtils.getDatacenter(VmwareUtils.java:33)
at jetbrains.buildServer.clouds.vmware.connector.VmwareInstance.<init>(VmwareInstance.java:55)
at jetbrains.buildServer.clouds.vmware.connector.VMWareApiConnectorImpl.listImageInstances(VMWareApiConnectorImpl.java:218)
at jetbrains.buildServer.clouds.vmware.connector.VMWareApiConnectorImpl.listImageInstances(VMWareApiConnectorImpl.java:53)
at jetbrains.buildServer.clouds.base.tasks.UpdateInstancesTask.run(UpdateInstancesTask.java:59)
at jetbrains.buildServer.util.NamedThreadFactory.executeWithNewThreadName(NamedThreadFactory.java:89)
at jetbrains.buildServer.clouds.base.connector.CloudAsyncTaskExecutor$2.run(CloudAsyncTaskExecutor.java:62)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)
Caused by: java.rmi.RemoteException: VI SDK invoke exception:com.vmware.vim25.ManagedObjectNotFound
at com.vmware.vim25.ws.WSClient.invoke(WSClient.java:122)
at com.vmware.vim25.ws.VimStub.retrieveProperties(VimStub.java:72)
at com.vmware.vim25.mo.PropertyCollector.retrieveProperties(PropertyCollector.java:107)
at com.vmware.vim25.mo.ManagedObject.retrieveObjectProperties(ManagedObject.java:155)
... 17 more
```

**Comment by nap** [comment]
There's the setup of the VM for which this error happened.

![screen shot 2017-02-08 at 10 54 36 am](https://cloud.githubusercontent.com/assets/2131451/22745031/2db40cf8-eded-11e6-85ff-9a4da71b83fb.png)

![screen shot 2017-02-08 at 10 55 04 am](https://cloud.githubusercontent.com/assets/2131451/22745038/37c3f0be-eded-11e6-83b1-dd5f326b959e.png)

**Comment by paksv** [comment]
apparently, TC tries to find the datacenter containing the VM and fails, because there's no datacenter in vSphere. I'll make the necessary fix.

**Comment by nap** [comment]
That's odd.

I do have a datacenter setup (PowerCLI is able to get it).
```
PS C:\Windows\system32> Get-Datacenter -VM cx-ui-nodejs-34318

Name                                    
----                                    
Build       
```

**Comment by nap** [comment]
Any thoughts on this?

**Comment by paksv** [comment]
maybe the user you are running under doesn't have an access to read the datacenter name?

**Comment by nap** [comment]
I thought so too but after validating the permissions on the user, everything seems to be in order.
I also ran the `Get-Datacenter` PowerCLI cmdlet as that specific user and it worked.

**Comment by nap** [comment]
Hey, I was wondering if you had time to work on a fix for that?
Thanks.

**Comment by deboj** [comment]
hi this is also affecting me heavily as well, making my teamcity server basically unusable

**Comment by paksv** [comment]
@nap I think it makes sense for you to update the plugin. Currently, latest version is 0.5.161 (https://teamcity.jetbrains.com/viewType.html?buildTypeId=TeamCityPluginsByJetBrains_TeamcityVmwarePlugin_Build) and judging from code. This situation is handled properly.

@deboj please post stacktrace here.

**Comment by nap** [comment]
@paksv I did the plugin update unfortunately I still get errors related to this. But now, at some point, the plugin will just stop functioning and throw the following endlessly:

```
[2017-07-11 10:06:06,080]  DEBUG [8 Flush Queue 1] - clouds.vmware.VmwareCloudImage - Instances count: 3 [TW-test-97955, TW-test-97956, TW-test-97957], can start more: true 
[2017-07-11 10:06:06,108]   INFO [8 Flush Queue 1] - clouds.vmware.VmwareCloudImage - Will create a new VM with name TW-test-97979 
[2017-07-11 10:06:06,129]   INFO [8 Flush Queue 1] - clouds.vmware.VmwareCloudImage - Will clone for TW-test-97979: true 
[2017-07-11 10:06:06,303]   WARN [re'{id=vmw-1} 2] - nnector.CloudAsyncTaskExecutor - An error occurred during checkTasks: java.lang.RuntimeException: java.rmi.RemoteException: VI SDK invoke exception:com.vmware.vim25.ManagedObjectNotFound 
[2017-07-11 10:06:06,303]  DEBUG [re'{id=vmw-1} 2] - nnector.CloudAsyncTaskExecutor - An error occurred during checkTasks 
java.lang.RuntimeException: java.rmi.RemoteException: VI SDK invoke exception:com.vmware.vim25.ManagedObjectNotFound
	at com.vmware.vim25.mo.ManagedObject.retrieveObjectProperties(ManagedObject.java:158)
	at com.vmware.vim25.mo.ManagedObject.getCurrentProperty(ManagedObject.java:179)
	at com.vmware.vim25.mo.Task.getTaskInfo(Task.java:62)
	at jetbrains.buildServer.clouds.vmware.connector.VmwareTaskWrapper$2.isDone(VmwareTaskWrapper.java:100)
	at jetbrains.buildServer.clouds.base.connector.CloudAsyncTaskExecutor.checkTasks(CloudAsyncTaskExecutor.java:87)
	at jetbrains.buildServer.clouds.base.connector.CloudAsyncTaskExecutor.access$000(CloudAsyncTaskExecutor.java:34)
	at jetbrains.buildServer.clouds.base.connector.CloudAsyncTaskExecutor$1.run(CloudAsyncTaskExecutor.java:48)
	at jetbrains.buildServer.util.NamedThreadFactory.executeWithNewThreadName(NamedThreadFactory.java:89)
	at jetbrains.buildServer.clouds.base.connector.CloudAsyncTaskExecutor$2.run(CloudAsyncTaskExecutor.java:65)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.rmi.RemoteException: VI SDK invoke exception:com.vmware.vim25.ManagedObjectNotFound
	at com.vmware.vim25.ws.WSClient.invoke(WSClient.java:122)
	at com.vmware.vim25.ws.VimStub.retrieveProperties(VimStub.java:72)
	at com.vmware.vim25.mo.PropertyCollector.retrieveProperties(PropertyCollector.java:107)
	at com.vmware.vim25.mo.ManagedObject.retrieveObjectProperties(ManagedObject.java:155)
	... 15 more
[2017-07-11 10:06:06,606]   WARN [re'{id=vmw-1} 2] - nnector.CloudAsyncTaskExecutor - An error occurred during checkTasks: java.lang.RuntimeException: java.rmi.RemoteException: VI SDK invoke exception:com.vmware.vim25.ManagedObjectNotFound 
[2017-07-11 10:06:06,606]  DEBUG [re'{id=vmw-1} 2] - nnector.CloudAsyncTaskExecutor - An error occurred during checkTasks 
java.lang.RuntimeException: java.rmi.RemoteException: VI SDK invoke exception:com.vmware.vim25.ManagedObjectNotFound
	at com.vmware.vim25.mo.ManagedObject.retrieveObjectProperties(ManagedObject.java:158)
	at com.vmware.vim25.mo.ManagedObject.getCurrentProperty(ManagedObject.java:179)
	at com.vmware.vim25.mo.Task.getTaskInfo(Task.java:62)
	at jetbrains.buildServer.clouds.vmware.connector.VmwareTaskWrapper$2.isDone(VmwareTaskWrapper.java:100)
	at jetbrains.buildServer.clouds.base.connector.CloudAsyncTaskExecutor.checkTasks(CloudAsyncTaskExecutor.java:87)
	at jetbrains.buildServer.clouds.base.connector.CloudAsyncTaskExecutor.access$000(CloudAsyncTaskExecutor.java:34)
	at jetbrains.buildServer.clouds.base.connector.CloudAsyncTaskExecutor$1.run(CloudAsyncTaskExecutor.java:48)
	at jetbrains.buildServer.util.NamedThreadFactory.executeWithNewThreadName(NamedThreadFactory.java:89)
	at jetbrains.buildServer.clouds.base.connector.CloudAsyncTaskExecutor$2.run(CloudAsyncTaskExecutor.java:65)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.rmi.RemoteException: VI SDK invoke exception:com.vmware.vim25.ManagedObjectNotFound
	at com.vmware.vim25.ws.WSClient.invoke(WSClient.java:122)
	at com.vmware.vim25.ws.VimStub.retrieveProperties(VimStub.java:72)
	at com.vmware.vim25.mo.PropertyCollector.retrieveProperties(PropertyCollector.java:107)
	at com.vmware.vim25.mo.ManagedObject.retrieveObjectProperties(ManagedObject.java:155)
	... 15 more
[2017-07-11 10:06:06,910]   WARN [re'{id=vmw-1} 2] - nnector.CloudAsyncTaskExecutor - An error occurred during checkTasks: java.lang.RuntimeException: java.rmi.RemoteException: VI SDK invoke exception:com.vmware.vim25.ManagedObjectNotFound 
[2017-07-11 10:06:06,910]  DEBUG [re'{id=vmw-1} 2] - nnector.CloudAsyncTaskExecutor - An error occurred during checkTasks 
java.lang.RuntimeException: java.rmi.RemoteException: VI SDK invoke exception:com.vmware.vim25.ManagedObjectNotFound
	at com.vmware.vim25.mo.ManagedObject.retrieveObjectProperties(ManagedObject.java:158)
	at com.vmware.vim25.mo.ManagedObject.getCurrentProperty(ManagedObject.java:179)
	at com.vmware.vim25.mo.Task.getTaskInfo(Task.java:62)
	at jetbrains.buildServer.clouds.vmware.connector.VmwareTaskWrapper$2.isDone(VmwareTaskWrapper.java:100)
	at jetbrains.buildServer.clouds.base.connector.CloudAsyncTaskExecutor.checkTasks(CloudAsyncTaskExecutor.java:87)
	at jetbrains.buildServer.clouds.base.connector.CloudAsyncTaskExecutor.access$000(CloudAsyncTaskExecutor.java:34)
	at jetbrains.buildServer.clouds.base.connector.CloudAsyncTaskExecutor$1.run(CloudAsyncTaskExecutor.java:48)
	at jetbrains.buildServer.util.NamedThreadFactory.executeWithNewThreadName(NamedThreadFactory.java:89)
	at jetbrains.buildServer.clouds.base.connector.CloudAsyncTaskExecutor$2.run(CloudAsyncTaskExecutor.java:65)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.rmi.RemoteException: VI SDK invoke exception:com.vmware.vim25.ManagedObjectNotFound
	at com.vmware.vim25.ws.WSClient.invoke(WSClient.java:122)
	at com.vmware.vim25.ws.VimStub.retrieveProperties(VimStub.java:72)
	at com.vmware.vim25.mo.PropertyCollector.retrieveProperties(PropertyCollector.java:107)
	at com.vmware.vim25.mo.ManagedObject.retrieveObjectProperties(ManagedObject.java:155)
	... 15 more
[2017-07-11 10:06:07,214]   WARN [re'{id=vmw-1} 2] - nnector.CloudAsyncTaskExecutor - An error occurred during checkTasks: java.lang.RuntimeException: java.rmi.RemoteException: VI SDK invoke exception:com.vmware.vim25.ManagedObjectNotFound 
[2017-07-11 10:06:07,214]  DEBUG [re'{id=vmw-1} 2] - nnector.CloudAsyncTaskExecutor - An error occurred during checkTasks 
java.lang.RuntimeException: java.rmi.RemoteException: VI SDK invoke exception:com.vmware.vim25.ManagedObjectNotFound
	at com.vmware.vim25.mo.ManagedObject.retrieveObjectProperties(ManagedObject.java:158)
	at com.vmware.vim25.mo.ManagedObject.getCurrentProperty(ManagedObject.java:179)
	at com.vmware.vim25.mo.Task.getTaskInfo(Task.java:62)
	at jetbrains.buildServer.clouds.vmware.connector.VmwareTaskWrapper$2.isDone(VmwareTaskWrapper.java:100)
	at jetbrains.buildServer.clouds.base.connector.CloudAsyncTaskExecutor.checkTasks(CloudAsyncTaskExecutor.java:87)
	at jetbrains.buildServer.clouds.base.connector.CloudAsyncTaskExecutor.access$000(CloudAsyncTaskExecutor.java:34)
	at jetbrains.buildServer.clouds.base.connector.CloudAsyncTaskExecutor$1.run(CloudAsyncTaskExecutor.java:48)
	at jetbrains.buildServer.util.NamedThreadFactory.executeWithNewThreadName(NamedThreadFactory.java:89)
	at jetbrains.buildServer.clouds.base.connector.CloudAsyncTaskExecutor$2.run(CloudAsyncTaskExecutor.java:65)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.rmi.RemoteException: VI SDK invoke exception:com.vmware.vim25.ManagedObjectNotFound
	at com.vmware.vim25.ws.WSClient.invoke(WSClient.java:122)
	at com.vmware.vim25.ws.VimStub.retrieveProperties(VimStub.java:72)
	at com.vmware.vim25.mo.PropertyCollector.retrieveProperties(PropertyCollector.java:107)
	at com.vmware.vim25.mo.ManagedObject.retrieveObjectProperties(ManagedObject.java:155)
	... 15 more

```
