### ISSUE TITLE
NullPointerException When Not Granted Root Administrator Access

### ISSUE THREAD

**Issue by StrangeWill** [JetBrains/teamcity-vmware-plugin#14]
Prior to v10, I was able to lock down the VMware user to a specific folder, network, and datastore, but now that I do that I get a null reference exception while fetching parameter values when configuring my system. I can grant admin, configure, then revoke and everything works fine, but ideally I shouldn't have to do this. It seems to be when querying Resource Pool information but I'm not sure how to grant access to that only... I would imagine a fallback would be to only list "Default".

	[2017-04-30 17:23:21,502]   WARN [nio-8111-exec-7] - eb.VMWareEditProfileController - Unable to get vCenter details: java.lang.NullPointerException
	java.lang.NullPointerException
			at java.util.Arrays.stream(Arrays.java:5004)
			at jetbrains.buildServer.clouds.vmware.connector.VMWareApiConnectorImpl.lambda$findAllResourcePools$6(VMWareApiConnectorImpl.java:336)
			at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:267)
			at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
			at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
			at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
			at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
			at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
			at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
			at jetbrains.buildServer.clouds.vmware.connector.VMWareApiConnectorImpl.findWithDatacenter(VMWareApiConnectorImpl.java:370)
			at jetbrains.buildServer.clouds.vmware.connector.VMWareApiConnectorImpl.findAllResourcePools(VMWareApiConnectorImpl.java:330)
			at jetbrains.buildServer.clouds.vmware.connector.VMWareApiConnectorImpl.getResourcePools(VMWareApiConnectorImpl.java:521)
			at jetbrains.buildServer.clouds.vmware.web.VMWareEditProfileController.doPost(VMWareEditProfileController.java:107)
			at jetbrains.buildServer.controllers.BaseFormXmlController$1.handleRequest(BaseFormXmlController.java:53)
			at jetbrains.buildServer.controllers.AjaxRequestProcessor.processRequest(AjaxRequestProcessor.java:45)
			at jetbrains.buildServer.controllers.BaseFormXmlController.doHandle(BaseFormXmlController.java:51)
			at jetbrains.buildServer.controllers.BaseController.handleRequestInternal(BaseController.java:75)
			at org.springframework.web.servlet.mvc.AbstractController.handleRequest(AbstractController.java:147)
			at org.springframework.web.servlet.mvc.SimpleControllerHandlerAdapter.handle(SimpleControllerHandlerAdapter.java:50)
			at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:961)
			at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:895)
			at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:967)
			at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:869)
			at javax.servlet.http.HttpServlet.service(HttpServlet.java:650)
			at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:843)
			at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
			at jetbrains.buildServer.maintenance.TeamCityDispatcherServlet.processedByMainServlet(TeamCityDispatcherServlet.java:27)
			at jetbrains.buildServer.maintenance.TeamCityDispatcherServlet.service(TeamCityDispatcherServlet.java:12)
			at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
			at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
			at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
			at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
			at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
			at jetbrains.buildServer.web.CSRFFilter.doFilter(CSRFFilter.java:90)
			at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
			at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
			at jetbrains.buildServer.web.jsp.JspPrecompilerFilter.doFilter(JspPrecompilerFilter.java:33)
			at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
			at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
			at jetbrains.buildServer.web.DisableSessionIdFromUrlFilter.doFilter(DisableSessionIdFromUrlFilter.java:5)
			at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
			at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
			at org.springframework.web.filter.CompositeFilter$VirtualFilterChain.doFilter(CompositeFilter.java:107)
			at jetbrains.buildServer.diagnostic.web.DiagnosticFilter.doFilter(DiagnosticFilter.java:18)
			at org.springframework.web.filter.CompositeFilter$VirtualFilterChain.doFilter(CompositeFilter.java:112)
			at jetbrains.buildServer.web.DependencyParametersCalculationContextFilter.doFilter(DependencyParametersCalculationContextFilter.java:3)
			at org.springframework.web.filter.CompositeFilter$VirtualFilterChain.doFilter(CompositeFilter.java:112)
			at org.springframework.web.filter.CompositeFilter.doFilter(CompositeFilter.java:73)
			at jetbrains.buildServer.web.DelegatingFilter.doFilter(DelegatingFilter.java:6)
			at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
			at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
			at jetbrains.buildServer.web.ResponseFragmentFilter.doFilter(ResponseFragmentFilter.java:4)
			at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
			at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
			at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
			at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
			at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:169)
			at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
			at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
			at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:436)
			at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1078)
			at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:625)
			at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1757)
			at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1716)
			at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
			at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
			at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
			at java.lang.Thread.run(Thread.java:745)

**Comment by paksv** [comment]
Hi, I tried to handle this in 2017.1.1. Please give it a try

**Comment by vputsenko** [comment]
Hello, 
We got this issue with 2017.1.1 (build 46654) update. Do you plan to fix this issue? It is absolutely regress, because previous TC 2017 version worked fine. Since it is not acceptable for to us to keep opened root rights, we are going to open support ticket.

**Comment by StrangeWill** [comment]
@vputsenko, a workaround is to grant rights, configure your cloud agents, then revoke them.

If you're not configuring cloud agents often, it's a good workaround until it's fixed.

**Comment by vputsenko** [comment]
Thanks for fast response, will discuss this with our administrators...

**Comment by paksv** [comment]
@StrangeWill can you please post log/stackstrace?

**Comment by StrangeWill** [comment]
@paksv they should be in the first post.

**Comment by paksv** [comment]
it's different from what it should be in 2017.1.1. I need to understand better what particular data is not available.

**Comment by StrangeWill** [comment]
@paksv Ah, that wasn't me that was on 2017.1.1 that said it still wasn't working, but I went ahead and upgraded to get you that stack trace:

    [2017-05-10 12:49:41,363]   WARN [nio-8111-exec-2] - eb.VMWareEditProfileController - Unable to get vCenter details: java.lang.NullPointerException
java.lang.NullPointerException
        at java.util.Arrays.stream(Arrays.java:5004)
        at jetbrains.buildServer.clouds.vmware.connector.VMWareApiConnectorImpl.lambda$findAllResourcePools$6(VMWareApiConnectorImpl.java:356)
        at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:267)
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
        at jetbrains.buildServer.clouds.vmware.connector.VMWareApiConnectorImpl.findWithDatacenter(VMWareApiConnectorImpl.java:398)
        at jetbrains.buildServer.clouds.vmware.connector.VMWareApiConnectorImpl.findAllResourcePools(VMWareApiConnectorImpl.java:352)
        at jetbrains.buildServer.clouds.vmware.connector.VMWareApiConnectorImpl.getResourcePools(VMWareApiConnectorImpl.java:547)
        at jetbrains.buildServer.clouds.vmware.web.VMWareEditProfileController.doPost(VMWareEditProfileController.java:109)
        at jetbrains.buildServer.controllers.BaseFormXmlController$1.handleRequest(BaseFormXmlController.java:54)
        at jetbrains.buildServer.controllers.AjaxRequestProcessor.processRequest(AjaxRequestProcessor.java:45)
        at jetbrains.buildServer.controllers.BaseFormXmlController.doHandle(BaseFormXmlController.java:52)
        at jetbrains.buildServer.controllers.BaseController.handleRequestInternal(BaseController.java:75)
        at org.springframework.web.servlet.mvc.AbstractController.handleRequest(AbstractController.java:147)
        at org.springframework.web.servlet.mvc.SimpleControllerHandlerAdapter.handle(SimpleControllerHandlerAdapter.java:50)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:961)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:895)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:967)
        at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:869)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:650)
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:843)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
        at jetbrains.buildServer.maintenance.TeamCityDispatcherServlet.processedByMainServlet(TeamCityDispatcherServlet.java:50)
        at jetbrains.buildServer.maintenance.TeamCityDispatcherServlet.service(TeamCityDispatcherServlet.java:46)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at jetbrains.buildServer.web.jsp.JspPrecompilerFilter.doFilter(JspPrecompilerFilter.java:129)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at jetbrains.buildServer.web.DisableSessionIdFromUrlFilter.doFilter(DisableSessionIdFromUrlFilter.java:5)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.springframework.web.filter.CompositeFilter$VirtualFilterChain.doFilter(CompositeFilter.java:107)
        at jetbrains.buildServer.diagnostic.web.DiagnosticFilter.doFilter(DiagnosticFilter.java:84)
        at org.springframework.web.filter.CompositeFilter$VirtualFilterChain.doFilter(CompositeFilter.java:112)
        at jetbrains.buildServer.web.DependencyParametersCalculationContextFilter.doFilter(DependencyParametersCalculationContextFilter.java:2)
        at org.springframework.web.filter.CompositeFilter$VirtualFilterChain.doFilter(CompositeFilter.java:112)
        at jetbrains.buildServer.web.CSRFFilter.doFilter(CSRFFilter.java:100)
        at org.springframework.web.filter.CompositeFilter$VirtualFilterChain.doFilter(CompositeFilter.java:112)
        at org.springframework.web.filter.CompositeFilter.doFilter(CompositeFilter.java:73)
        at jetbrains.buildServer.web.DelegatingFilter.doFilter(DelegatingFilter.java:37)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at jetbrains.buildServer.web.ResponseFragmentFilter.doFilter(ResponseFragmentFilter.java:5)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:169)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:436)
        at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1078)
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:625)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1757)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1716)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:745)

**Comment by paksv** [comment]
[cloud-vmware.zip](https://github.com/JetBrains/teamcity-vmware-plugin/files/990853/cloud-vmware.zip)

Please try the fix and let me know if it helps.

**Comment by StrangeWill** [comment]
Works for me 👍
